2020-07-19 23:24:56,758 - login.py - INFO - 登录失败TestData:im.wangziyi,qwer1234...
2020-07-19 23:25:50,045 - login.py - INFO - 登录失败,TestData:im.wangziyi,qwer1234...
2020-07-19 23:26:57,049 - login.py - INFO - 登录失败!TestData:im.wangziyi,qwer1234...
2020-07-19 23:27:36,858 - login.py - INFO - 登录失败!TestData:im.wangziyi,qwer1234...
2020-07-19 23:28:29,135 - login.py - INFO - 登录失败!TestData:im.wangziyi,qwer1234...
2020-07-19 23:29:06,460 - login.py - INFO - 登录失败!TestData:im.wangziyi,qwer1234...
2020-07-19 23:30:08,320 - login.py - INFO - 登录失败!          TestData:im.wangziyi,qwer1234...
2020-07-19 23:31:10,291 - login.py - INFO - 登录失败!          TestData:im.wangziyi,qwer1234...
2020-07-19 23:32:51,103 - login.py - INFO - 登录失败~~~~~~~~~~~~TestData:im.wangziyi,qwer1234...
2020-07-21 00:19:36,129 - connectionpool.py - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0368E6E8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9a75e0b6f0c32384fa626a5bb45d68dc/url
2020-07-21 00:19:38,142 - connectionpool.py - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0395CEE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9a75e0b6f0c32384fa626a5bb45d68dc/url
2020-07-21 00:19:40,149 - connectionpool.py - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0395CF58>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/9a75e0b6f0c32384fa626a5bb45d68dc/url
2020-07-21 00:21:14,805 - connectionpool.py - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0424E6E8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/59cfb5c262c2d579621eeac09f7f4a0e/url
2020-07-21 00:21:16,807 - connectionpool.py - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0454BEE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/59cfb5c262c2d579621eeac09f7f4a0e/url
2020-07-21 00:21:18,809 - connectionpool.py - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0454BF58>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/59cfb5c262c2d579621eeac09f7f4a0e/url
2020-07-21 00:24:30,106 - connectionpool.py - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03E0D700>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/59657a2512faa81b811db9e7fac6a486/url
2020-07-21 00:24:32,108 - connectionpool.py - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04135088>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/59657a2512faa81b811db9e7fac6a486/url
2020-07-21 00:24:34,113 - connectionpool.py - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04135130>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/59657a2512faa81b811db9e7fac6a486/url
2020-07-21 00:24:38,122 - connectionpool.py - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04135268>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/59657a2512faa81b811db9e7fac6a486/url
2020-07-21 00:24:40,124 - connectionpool.py - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04135508>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/59657a2512faa81b811db9e7fac6a486/url
2020-07-21 00:24:42,127 - connectionpool.py - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x041355E0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/59657a2512faa81b811db9e7fac6a486/url
2020-07-21 00:26:50,633 - connectionpool.py - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x039DC700>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/284b80d7903cbb85ae77ffa52be0302a/url
2020-07-21 00:26:52,637 - connectionpool.py - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03AABD60>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/284b80d7903cbb85ae77ffa52be0302a/url
2020-07-21 00:26:54,642 - connectionpool.py - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03AD60A0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/284b80d7903cbb85ae77ffa52be0302a/url
2020-07-21 00:39:39,679 - connectionpool.py - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0360D700>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/0125383e0e9959e3f37044cf05a0f967/url
2020-07-21 00:39:41,684 - connectionpool.py - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x038D7E68>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/0125383e0e9959e3f37044cf05a0f967/url
2020-07-21 00:39:43,686 - connectionpool.py - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x038D7EE0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/0125383e0e9959e3f37044cf05a0f967/url
2020-07-21 00:46:11,779 - connectionpool.py - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0343D700>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/ad304b7a4f96a40a50f4589fdd2a9818/url
2020-07-21 00:46:13,784 - connectionpool.py - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03938E80>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/ad304b7a4f96a40a50f4589fdd2a9818/url
2020-07-21 00:46:15,787 - connectionpool.py - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03938EF8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/ad304b7a4f96a40a50f4589fdd2a9818/url
2020-07-21 00:48:45,940 - connectionpool.py - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0380F748>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b07f5774747ddf0e276025a27b235daf/url
2020-07-21 00:48:47,946 - connectionpool.py - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03ADBE98>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b07f5774747ddf0e276025a27b235daf/url
2020-07-21 00:48:49,949 - connectionpool.py - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03ADBF10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/b07f5774747ddf0e276025a27b235daf/url
2020-07-21 00:49:31,243 - connectionpool.py - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x034CF748>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/896f83ec997f73510c4ee69a1979a232/url
2020-07-21 00:49:33,245 - connectionpool.py - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0379BEB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/896f83ec997f73510c4ee69a1979a232/url
2020-07-21 00:49:59,035 - connectionpool.py - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0323F748>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/f1e401655d6b4a4d219b1ce559bbafdc/url
2020-07-21 00:50:01,035 - connectionpool.py - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0350BE98>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/f1e401655d6b4a4d219b1ce559bbafdc/url
2020-07-21 00:50:03,037 - connectionpool.py - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0350BF10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/f1e401655d6b4a4d219b1ce559bbafdc/url
2020-07-22 21:55:43,049 - connectionpool.py - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03CCF748>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/a7c1b59132d0797aa2540537bf48cba1/url
2020-07-22 21:55:45,061 - connectionpool.py - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03F9BEC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/a7c1b59132d0797aa2540537bf48cba1/url
2020-07-22 21:55:47,065 - connectionpool.py - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03F9BF40>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/a7c1b59132d0797aa2540537bf48cba1/url
2020-07-22 21:58:03,073 - connectionpool.py - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x032BF748>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8abfd4fe30434822871ebe1073b9a834/url
2020-07-22 21:58:05,077 - connectionpool.py - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x037AAE98>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8abfd4fe30434822871ebe1073b9a834/url
2020-07-22 21:58:07,081 - connectionpool.py - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x037AAF10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8abfd4fe30434822871ebe1073b9a834/url
2020-07-22 22:05:18,151 - connectionpool.py - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03E1D7D8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8e65589acf77b93ccd67a3b67b109e9d/url
2020-07-22 22:05:20,154 - connectionpool.py - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x04135040>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8e65589acf77b93ccd67a3b67b109e9d/url
2020-07-22 22:05:22,157 - connectionpool.py - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x041350E8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/8e65589acf77b93ccd67a3b67b109e9d/url
2020-07-22 22:17:38,664 - connectionpool.py - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0359F748>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/fd62846eae99c1b1ba911a00b90bc1d5/url
2020-07-22 22:17:40,665 - connectionpool.py - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03A6EF88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/fd62846eae99c1b1ba911a00b90bc1d5/url
2020-07-22 22:17:42,670 - connectionpool.py - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x03A9C0B8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')': /session/fd62846eae99c1b1ba911a00b90bc1d5/url
2020-07-22 22:19:00,828 - TeatCase1.py - INFO - 失败~~~~~~~~~~~~TestData:im.wangziyi,qwer1234...
2020-07-22 22:24:21,014 - TeatCase2.py - INFO - 失败~~~~~~~~~~~~TestData:im.wangziyi,qwer1234....
2020-07-22 22:31:50,015 - TeatCase2.py - INFO - 用例执行失败~~~~~~~~~~~~TestData:im.wangziyi,qwer1234....
2020-07-22 22:32:49,058 - TeatCase2.py - INFO - 用例执行失败~~~~~~~~~~~~TestData:im.wangziyi,qwer1234....
2020-07-22 22:36:22,460 - TeatCase2.py - INFO - 用例执行失败~~~~~~~~~~~~TestData:im.wangziyi,qwer1234....
2020-07-22 22:37:08,102 - TeatCase2.py - INFO - 用例执行失败~~~~~~~~~~~~TestData:im.wangziyi,qwer1234....
2020-07-22 22:42:55,456 - TeatCase1.py - INFO - 用例执行失败~~~~~~~~~~~~TestData:im.wangziyi,qwer1234...
2020-07-22 22:44:05,195 - TeatCase1.py - INFO - 用例执行失败~~~~~~~~~~~~TestData:im.wangziyi,qwer1234...
